version: "3.9"

services:
  backend:
    build: ./backend
    image: pranshu244/cgpapredictor-backend:latest
    container_name: cgpa-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api.log:/app/api.log

  frontend:
    build: ./frontend
    image: pranshu244/cgpapredictor-frontend:latest
    container_name: cgpa-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend